Repository stimulusreflex/stimulus_reflex, pull requests merged in 2020-05, with the labels that each got.

#160 add reflex callbacks
  lib/stimulus_reflex/channel.rb
  lib/stimulus_reflex/reflex.rb
Labels: enhancement

#180 Allow channel exceptions to be rescuable
  lib/stimulus_reflex/channel.rb
  lib/stimulus_reflex/reflex.rb
Labels: enhancement

#181 Replace uuid4 dependency with function in repo
  javascript/package.json
  javascript/stimulus_reflex.js
  javascript/yarn.lock
Labels: enhancement

#184 Replace camelize with homegrown version
  javascript/lifecycle.js
  javascript/package.json
  javascript/yarn.lock
Labels: enhancement

#178 Pluralize the generated class name, so that will match with the file name
  CHANGELOG.md
  lib/generators/stimulus_reflex_generator.rb
  lib/generators/templates/custom_controller.js
  lib/generators/templates/custom_reflex.rb
  test/generators/stimulus_reflex_generator_test.rb
Labels: bug

#191 Add guard to morph that checks stimulusReflex
  javascript/stimulus_reflex.js
Labels: bug

#197 Setup mutation aware declarative reflexes
  javascript/stimulus_reflex.js
  javascript/utils.js
Labels: enhancement

#204 Form parameters
  javascript/package.json
  javascript/stimulus_reflex.js
  javascript/yarn.lock
  lib/generators/templates/custom_reflex.rb
  lib/stimulus_reflex/channel.rb
  lib/stimulus_reflex/reflex.rb
Labels: enhancement

#198 Small typo/grammar fix in quickstart doc.
  docs/quickstart.md
Labels: documentation

#210 Make element even more user friendly
  lib/stimulus_reflex/element.rb
Labels: enhancement

#212 reflex_name restriction loosening
  lib/stimulus_reflex/channel.rb
Labels: enhancement

#200 Combine dataset with data-attributes from parent elements on reflex call
  javascript/attributes.js
  javascript/schema.js
  javascript/stimulus_reflex.js
  javascript/test/attributes.extractDataAttributes.test.js
  javascript/test/attributes.extractElementDataset.test.js
  javascript/yarn.lock
  lib/stimulus_reflex/channel.rb
  lib/stimulus_reflex/element.rb
Labels: enhancement

#203 Map hashes in incoming arguments using with_indifferent_access
  lib/stimulus_reflex/channel.rb
Labels: enhancement

#220 Fix multipleInstances convenience method
  javascript/attributes.js
Labels: bug
