Repository stimulusreflex/stimulus_reflex, pull requests merged in 2020-07, with the labels that each got.

#256 Limit MutationObserver mutations
  javascript/stimulus_reflex.js
Labels: bug

#211 Morph Modes: page, selector and nothing
  docs/scoping.md
  javascript/lifecycle.js
  javascript/log.js
  javascript/stimulus_reflex.js
  lib/stimulus_reflex.rb
  lib/stimulus_reflex/broadcaster.rb
  lib/stimulus_reflex/channel.rb
  lib/stimulus_reflex/morph_mode.rb
  lib/stimulus_reflex/morph_mode/nothing_morph_mode.rb
  lib/stimulus_reflex/morph_mode/page_morph_mode.rb
  lib/stimulus_reflex/morph_mode/selector_morph_mode.rb
  lib/stimulus_reflex/reflex.rb
Labels: enhancement

#276 Simplify devise authentication logic (in docs)
  docs/authentication.md
Labels: documentation
