Repository stimulusreflex/stimulus_reflex, pull requests merged in 2020-04, with the labels that each got.

#143 Create dynamic changelog
  .github/workflows/changelog.yml
  CHANGELOG.md
  Gemfile.lock
  Rakefile
  stimulus_reflex.gemspec
Labels: enhancement, proposal

#145 Allow other CableReady operations to perform
  javascript/stimulus_reflex.js
Labels: bug

#146 Attach element.tagName to extracted attributes
  docs/reflexes.md
  javascript/attributes.js
  javascript/test/attributes.extractElementAttributes.test.js
Labels: enhancement

#148 Check the ActionCable connection on stimuluate
  Gemfile.lock
  javascript/attributes.js
  javascript/consumer.js
  javascript/stimulus_reflex.js
  javascript/yarn.lock
Labels: enhancement

#150 remove changelog rake task
  .github/workflows/changelog.yml
  Gemfile.lock
  Rakefile
  stimulus_reflex.gemspec
Labels: bug

#158 Remove unneeded registerConsumer logic
  Gemfile.lock
  javascript/consumer.js
  javascript/package.json
  javascript/stimulus_reflex.js
  javascript/yarn.lock
Labels: bug
