Repository stimulusreflex/stimulus_reflex, pull requests merged in 2020-06, with the labels that each got.

#231 merges insteads of overwrites params for reflex actions with form data
  lib/stimulus_reflex/reflex.rb
Labels: bug

#234 __perform had a bug where it was only ever calling the first event
  javascript/stimulus_reflex.js
Labels: bug

#235 Add more smarts to __perform
  javascript/stimulus_reflex.js
Labels: bug

#230 adds params documentation
  docs/reflexes.md
Labels: documentation

#241 Update install.rake to handle Typescript
  lib/tasks/stimulus_reflex/install.rake
Labels: enhancement

#254 Returns more helpful error message if Reflex doesn't exist
  javascript/log.js
  lib/stimulus_reflex/channel.rb
Labels: enhancement
