Repository stimulusreflex/stimulus_reflex, pull requests merged in 2021-01, with the labels that each got.

#410 Prefix dom_id with hash/pound
  lib/stimulus_reflex/reflex.rb
  package.json
  test/reflex_test.rb
  yarn.lock
Labels: bug

#415 Add matrix strategy to ruby tests
  .github/workflows/tests.yml
Labels: infrastructure

#416 Bug fix: Updating changelog generator to push to master, not main
  .github/workflows/changelog.yml
Labels: bug, infrastructure

#418 encode form data for chars like '&' and '='
  javascript/test/utils.serializeForm.test.js
  javascript/utils.js
Labels: bug

#417 controller element holds Reflex metadata
  app/channels/stimulus_reflex/channel.rb
  javascript/log.js
  javascript/stimulus_reflex.js
  lib/stimulus_reflex/reflex.rb
Labels: enhancement, javascript

#431 life-cycle callbacks return correct element reference
  app/channels/stimulus_reflex/channel.rb
  javascript/attributes.js
  javascript/lifecycle.js
  javascript/stimulus_reflex.js
  javascript/utils.js
  lib/stimulus_reflex/reflex.rb
Labels: bug
