Repository stimulusreflex/stimulus_reflex, pull requests merged in 2021-09, with the labels that each got.

#528 Provide proxy methods truthy? and numeric on Element
  lib/stimulus_reflex/dataset.rb
  lib/stimulus_reflex/element.rb
  lib/stimulus_reflex/utils/attribute_builder.rb
  test/element_test.rb
Labels: proposal, ruby

#546 overhaul Reflex logging
  app/channels/stimulus_reflex/channel.rb
  lib/generators/stimulus_reflex/templates/config/initializers/stimulus_reflex.rb
  lib/stimulus_reflex/configuration.rb
  lib/stimulus_reflex/utils/logger.rb
Labels: enhancement, proposal, ruby

#547 document body connection status classes
  javascript/stimulus_reflex.js
  javascript/transports/action_cable.js
Labels: enhancement, proposal, javascript
