Repository stimulusreflex/stimulus_reflex, pull requests merged in 2021-05, with the labels that each got.

#498 render_collection
  lib/stimulus_reflex/broadcasters/selector_broadcaster.rb
  lib/stimulus_reflex/reflex.rb
Labels: proposal, ruby

#491 Log the full exception trace
  app/channels/stimulus_reflex/channel.rb
  lib/stimulus_reflex/broadcasters/broadcaster.rb
Labels: bug, enhancement, ruby

#478 data-reflex-dataset and data-reflex-dataset-all
  javascript/attributes.js
  javascript/schema.js
  javascript/stimulus_reflex.js
  javascript/test/attributes.extractElementDataset.test.js
  javascript/utils.js
  lib/stimulus_reflex/element.rb
  package.json
  test/element_test.rb
  yarn.lock
Labels: deprecated, javascript, proposal

#506 tab_id accessor
  javascript/stimulus_reflex.js
  lib/generators/stimulus_reflex/templates/app/reflexes/%file_name%_reflex.rb.tt
  lib/stimulus_reflex/reflex.rb
  lib/stimulus_reflex/reflex_data.rb
  lib/stimulus_reflex/reflex_factory.rb
Labels: enhancement, javascript, proposal, ruby

#485 delegate dom_id to CableReady::Identifiable
  lib/stimulus_reflex/broadcasters/selector_broadcaster.rb
  lib/stimulus_reflex/reflex.rb
Labels: cableready, enhancement, ruby

#509 handle operations that have string-defined selector argument
  Gemfile.lock
  lib/stimulus_reflex/cable_ready_channels.rb
Labels: bug, cableready, ruby
