Repository stimulusreflex/stimulus_reflex, pull requests merged in 2022-07, with the labels that each got.

#594 Extract StimulusReflex::Fragment
  lib/stimulus_reflex.rb
  lib/stimulus_reflex/broadcasters/page_broadcaster.rb
  lib/stimulus_reflex/broadcasters/selector_broadcaster.rb
  lib/stimulus_reflex/fragment.rb
Labels: enhancement

#600 missing safe navigation
  lib/stimulus_reflex/reflex.rb
Labels: bug

#599 configure operations for morph and replace
  lib/generators/stimulus_reflex/templates/config/initializers/stimulus_reflex.rb
  lib/stimulus_reflex/broadcasters/page_broadcaster.rb
  lib/stimulus_reflex/broadcasters/selector_broadcaster.rb
  lib/stimulus_reflex/configuration.rb
Labels: enhancement, proposal, cableready
